export enum DeploymentStatus {
    QUEUED = "QUEUED",
    CLONING = "CLONING",
    INSTALLING = "INSTALLING",
    BUILDING = "BUILDING",
    UPLOADING = "UPLOADING",
    SUCCESS = "SUCCESS",
    FAILED = "FAILED",
}